### PR TITLE
Added qtmultimedia to .pro file

### PR DESCRIPTION
**Pull request by Choochmeque**
Silence some warnings
Properly cleanup shared key pointer

### CODE REVIEW

**Comment by Choochmeque** [comment]
@realbardia, can you please review my pull request?

**Comment by realbardia** [comment]
I accepted this one time. I don't know why it's not accepted. Anyway sorry...

**Comment by realbardia** [comment]
And Thank You :)

**Comment by Choochmeque** [comment]
It's ok ;)

**Pull request merged**
